### ISSUE TITLE
[BUG] Everyone has Admin persmission

### ISSUE THREAD

**Issue by lildiznick** [qbcore-framework/qb-core#225]
**Describe the bug**
Since the update to both the new commit of qb-core and database index structure, everyone in server has access to admin menu and admin commands.
**To Reproduce**
login as a normal user, type /admin or any of the other admin only commands

**Expected behavior**
Only players set to admin or god have access to these functions

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: qb-core; this afternoon (newest commit with player nearby bug fix) database; yesterday
 - Are you using custom resource? which ones? n/a
 - Have you renamed `qb-` to something custom? no

**Additional context**
I've had several players that have been able to use these commands

**Comment by GhzGarage** [comment]
This is fixed now https://github.com/qbcore-framework/qb-core/commit/f2414d02759dbd7278753c19af9ddc77f5f5d86d

**Comment by lildiznick** [comment]
> This is fixed now [f2414d0](https://github.com/qbcore-framework/qb-core/commit/f2414d02759dbd7278753c19af9ddc77f5f5d86d)

Thanks so much!  This is an awesome framework!  Thanks for all of your hard work!

**Comment by lildiznick** [comment]
> This is fixed now [f2414d0](https://github.com/qbcore-framework/qb-core/commit/f2414d02759dbd7278753c19af9ddc77f5f5d86d)
I just tested in my server.  It still seems to be an issue.  I deleted myself from the permissions table in the database, restarted the server, and still have access to everything even with no permissions.  I'm trying to find someone to hop into the server to see if it happens with them as well.  Will keep you advised.
